### ISSUE TITLE
click module not included in default install

### ISSUE THREAD

**Issue by mane292** [davidkastner/pyEF#9]
Error: No module named "click" . This issue is fixed with "pip install click", but we should include this fix in the default installation? (Unless this is a result of specific Conda versions?)

**Comment by davidkastner** [comment]
I agree. The `environment.yml` file has been updated to include the `click` package in the default environment install. It is install using the conda package manager. I tested it and no longer throws the error `Error: No module named "click"`. The fix was incorporated in pull request #11.

**Comment by davidkastner** [comment]
I agree. The environment.yml file has been updated to include the click package in the default environment install. It is install using the conda package manager. I tested it and no longer throws the error Error: No module named "click". The fix was incorporated in pull request #11 .
